# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages



before_script:
  - docker info

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: gitlab/dind
  services:
    - docker:dind
  script:
    - echo "Compiling the code..."
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --tag "$CI_REGISTRY_IMAGE" --file hello-kubernete/src/app/Dockerfile hello-kubernete/src/app/
    - docker push $CI_REGISTRY_IMAGE
    - echo "Compile complete."



deploy-job:      # This job runs in the deploy stage.
  stage: deploy  
  image: google/cloud-sdk:alpine
  tags:
  - kube-runner
  script:
    - echo "Deploying application..."
    #- echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    #- gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    #- gcloud --quiet --project $PROJECT_ID app deploy hello-kubernete\deploy\helm\hello-kubernetes\values.yaml hello-kubernete\deploy\helm\hello-kubernetes\Chart.yaml
    #- helm upgrade hell-k8s hello-kubernete\deploy --install --namespace gl --timeout 30m0s
    - kubectl get node
    - echo "Application successfully deployed."
